"use client";

import React from "react";
import { toast } from "sonner";
import { AlertDialog, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Refresh, Copy } from "@solar-icons/react";
import { cn } from "@/lib/utils";
import { useGenerateCandidateInvite } from "@/hooks/use-candidates";

const RefreshCw = Refresh;

function copyText(text: string): void {
  const el = document.createElement("textarea");
  el.value = text;
  el.style.position = "fixed";
  el.style.opacity = "0";
  document.body.appendChild(el);
  el.select();
  document.execCommand("copy");
  document.body.removeChild(el);
}

const STATUS_BANNER: Record<string, string> = {
  Pending: "Link dan kode akses sudah siap. Silakan kirimkan ke kandidat untuk melengkapi data lamaran.",
  Viewed: "Kandidat sudah membuka link, belum menyelesaikan pengisian data.",
  Completed: "Kandidat sudah melengkapi data lamaran.",
};

export interface InviteCandidateModalProps {
  candidateId: string;
  candidateName: string;
  onClose: () => void;
}

export function InviteCandidateModal({ candidateId, candidateName, onClose }: InviteCandidateModalProps): React.JSX.Element {
  const [invite, setInvite] = React.useState<{ token: string; accessCode: string; status?: string } | null>(null);
  const [loading, setLoading] = React.useState(true);
  const [confirmRegen, setConfirmRegen] = React.useState(false);
  const generateMutation = useGenerateCandidateInvite();
  const autoGeneratedRef = React.useRef(false);

  const inviteUrl = invite ? `${window.location.origin}/apply-invite/${invite.token}` : null;

  const generate = React.useCallback(() => {
    generateMutation.mutate(candidateId, {
      onSuccess: (result) => {
        if (!result.success || !result.data) { toast.error(result.error ?? "Gagal generate link undangan"); return; }
        setConfirmRegen(false);
        setInvite({ token: result.data.token, accessCode: result.data.accessCode, status: "Pending" });
        toast.success("Link & kode akses baru di-generate");
      },
      onError: () => toast.error("Gagal generate link undangan"),
    });
  }, [candidateId, generateMutation]);

  React.useEffect(() => {
    let cancelled = false;
    autoGeneratedRef.current = false;
    setLoading(true);
    fetch(`/api/hr/candidates/${candidateId}/invite`)
      .then((res) => res.json())
      .then((data: { invite?: { token: string; accessCode: string; status: string } | null }) => {
        if (cancelled) return;
        if (data.invite) {
          setInvite(data.invite);
        } else if (!autoGeneratedRef.current) {
          // Belum pernah diundang — langsung generate link & kode, jangan
          // tampilkan layar kosong yang butuh klik "Generate Link" manual.
          autoGeneratedRef.current = true;
          generate();
        }
      })
      .catch(() => {})
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [candidateId]);

  const isPending = loading || generateMutation.isPending;

  return (
    <AlertDialog open onOpenChange={(open) => { if (!open) onClose(); }}>
      <AlertDialogContent className="sm:max-w-md!" style={{ width: "min(calc(100vw - 2rem), 28rem)" }} onClick={(e) => e.stopPropagation()}>
        <AlertDialogHeader>
          <AlertDialogTitle>Undangan Kandidat</AlertDialogTitle>
          <AlertDialogDescription>{candidateName}</AlertDialogDescription>
        </AlertDialogHeader>

        {loading ? (
          <div className={cn('flex', 'items-center', 'justify-center', 'py-8', 'gap-2', 'text-sm', 'text-muted-foreground')}>
            <RefreshCw weight="BoldDuotone" className={cn('h-4', 'w-4', 'animate-spin')} /> Loading...
          </div>
        ) : !invite ? (
          <div className={cn('flex', 'flex-col', 'items-center', 'justify-center', 'py-8', 'gap-3', 'text-center')}>
            <p className={cn('text-sm', 'text-muted-foreground')}>Belum ada link undangan untuk kandidat ini.</p>
            <Button size="sm" onClick={generate} disabled={isPending}>Generate Link</Button>
          </div>
        ) : (
          <div className={cn('space-y-3', 'py-1')}>
            {STATUS_BANNER[invite.status ?? "Pending"] && (
              <div className="rounded-lg border border-border bg-muted/50 p-2.5">
                <p className="text-xs text-muted-foreground font-medium">{STATUS_BANNER[invite.status ?? "Pending"]}</p>
              </div>
            )}
            <div className="space-y-1">
              <p className={cn('text-xs', 'text-muted-foreground', 'font-medium')}>Link Undangan</p>
              <div className={cn('flex', 'items-center', 'gap-2', 'overflow-hidden')}>
                <code className={cn('min-w-0', 'flex-1', 'text-xs', 'bg-muted', 'rounded', 'px-2', 'py-1.5', 'block', 'break-all')}>{inviteUrl}</code>
                <Button
                  variant="outline"
                  size="icon-sm"
                  onClick={() => {
                    copyText(`Silakan lengkapi data lamaran Anda melalui link berikut:\n${inviteUrl}\n\nKode Akses: ${invite.accessCode}`);
                    toast.success("Link & kode akses disalin");
                  }}
                >
                  <Copy weight="BoldDuotone" className={cn('h-3.5', 'w-3.5')} />
                </Button>
              </div>
            </div>
            <div className="space-y-1">
              <p className={cn('text-xs', 'text-muted-foreground', 'font-medium')}>Kode Akses</p>
              <div className={cn('flex', 'items-center', 'gap-2')}>
                <code className={cn('flex-1', 'text-lg', 'font-mono', 'font-bold', 'tracking-widest', 'bg-muted', 'rounded', 'px-2', 'py-1.5')}>{invite.accessCode}</code>
                <Button variant="outline" size="icon-sm" onClick={() => { copyText(invite.accessCode); toast.success("Kode disalin"); }}>
                  <Copy weight="BoldDuotone" className={cn('h-3.5', 'w-3.5')} />
                </Button>
              </div>
            </div>

            {confirmRegen ? (
              <div className="rounded-lg border border-destructive/30 bg-destructive/5 p-3 space-y-2.5">
                <p className="text-xs text-foreground font-medium">Generate ulang link & kode akses?</p>
                <p className="text-xs text-muted-foreground">Link dan kode lama akan langsung nonaktif dan diganti yang baru. Kalau kandidat sudah melengkapi data, link akan dibuka kembali.</p>
                <div className="flex items-center gap-2">
                  <Button size="sm" variant="destructive" className="rounded-full" onClick={generate} disabled={isPending}>
                    {isPending ? "Memproses..." : "Ya, Regenerate"}
                  </Button>
                  <Button size="sm" variant="ghost" className="rounded-full" onClick={() => setConfirmRegen(false)} disabled={isPending}>
                    Batal
                  </Button>
                </div>
              </div>
            ) : (
              <Button variant="outline" size="sm" className="w-full rounded-full" onClick={() => setConfirmRegen(true)} disabled={isPending}>
                <RefreshCw weight="BoldDuotone" className={cn('h-3.5', 'w-3.5', 'mr-1.5')} />
                Regenerate Link & Kode
              </Button>
            )}
          </div>
        )}

        <AlertDialogFooter>
          <AlertDialogCancel onClick={onClose}>Tutup</AlertDialogCancel>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
}
